[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "1"
path = "src/day1.rs"
[[bin]]
name = "2"
path = "src/day2.rs"
[[bin]]
name = "3"
path = "src/day3.rs"

[dependencies]
derive_more = { version = "1.0.0", features = ["debug", "display", "from"] }
regex = "1.11.1"
